package com.accp.email.dao;

import com.accp.email.pojo.Accessorybox;

public interface AccessoryboxDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessorybox
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer outbox_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessorybox
     *
     * @mbggenerated
     */
    int insert(Accessorybox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessorybox
     *
     * @mbggenerated
     */
    int insertSelective(Accessorybox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessorybox
     *
     * @mbggenerated
     */
    Accessorybox selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessorybox
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Accessorybox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessorybox
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Accessorybox record);
}