package com.accp.email.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.accp.email.pojo.Inbox;
import com.accp.email.vo.SelectVo;

public interface InboxDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer inboxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbggenerated
     */
    int insert(Inbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbggenerated
     */
    int insertSelective(Inbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbggenerated
     */
    Inbox selectByPrimaryKey(Integer inboxId);
    
    List<Inbox> selectByEid(SelectVo vo);
    
    List<Inbox> selectSizeByEid(String eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Inbox record);
    
    int updateStatus(@Param("inboxId")Integer id,@Param("remove_status")Integer remove_status);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Inbox record);
}