package com.accp.email.dao;

import java.util.List;

import com.accp.email.pojo.Inbox;
import com.accp.email.pojo.Outbox;
import com.accp.email.vo.SelectVo;

public interface OutboxDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbox
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer outboxId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbox
     *
     * @mbggenerated
     */
    int insert(Outbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbox
     *
     * @mbggenerated
     */
    int insertSelective(Outbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbox
     *
     * @mbggenerated
     */
    Outbox selectByPrimaryKey(Integer outboxId);
    
    List<Outbox> selectByEid(SelectVo vo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbox
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Outbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbox
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Outbox record);
}