package com.accp.email.pojo;

import java.io.Serializable;

public class Accessorybox implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accessorybox.aid
     *
     * @mbggenerated
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accessorybox.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accessorybox.inbox_id
     *
     * @mbggenerated
     */
    private Integer inboxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accessorybox.outbox_id
     *
     * @mbggenerated
     */
    private Integer outboxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table accessorybox
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accessorybox.aid
     *
     * @return the value of accessorybox.aid
     *
     * @mbggenerated
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accessorybox.aid
     *
     * @param aid the value for accessorybox.aid
     *
     * @mbggenerated
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accessorybox.path
     *
     * @return the value of accessorybox.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accessorybox.path
     *
     * @param path the value for accessorybox.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accessorybox.inbox_id
     *
     * @return the value of accessorybox.inbox_id
     *
     * @mbggenerated
     */
    public Integer getInboxId() {
        return inboxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accessorybox.inbox_id
     *
     * @param inboxId the value for accessorybox.inbox_id
     *
     * @mbggenerated
     */
    public void setInboxId(Integer inboxId) {
        this.inboxId = inboxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accessorybox.outbox_id
     *
     * @return the value of accessorybox.outbox_id
     *
     * @mbggenerated
     */
    public Integer getOutboxId() {
        return outboxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accessorybox.outbox_id
     *
     * @param outboxId the value for accessorybox.outbox_id
     *
     * @mbggenerated
     */
    public void setOutboxId(Integer outboxId) {
        this.outboxId = outboxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessorybox
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Accessorybox other = (Accessorybox) that;
        return (this.getAid() == null ? other.getAid() == null : this.getAid().equals(other.getAid()))
            && (this.getPath() == null ? other.getPath() == null : this.getPath().equals(other.getPath()))
            && (this.getInboxId() == null ? other.getInboxId() == null : this.getInboxId().equals(other.getInboxId()))
            && (this.getOutboxId() == null ? other.getOutboxId() == null : this.getOutboxId().equals(other.getOutboxId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessorybox
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAid() == null) ? 0 : getAid().hashCode());
        result = prime * result + ((getPath() == null) ? 0 : getPath().hashCode());
        result = prime * result + ((getInboxId() == null) ? 0 : getInboxId().hashCode());
        result = prime * result + ((getOutboxId() == null) ? 0 : getOutboxId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessorybox
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", aid=").append(aid);
        sb.append(", path=").append(path);
        sb.append(", inboxId=").append(inboxId);
        sb.append(", outboxId=").append(outboxId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}