package com.accp.email.pojo;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Inbox implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbox.inbox_id
     *
     * @mbggenerated
     */
    private Integer inboxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbox.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbox.topic
     *
     * @mbggenerated
     */
    private String topic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbox.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbox.read_status
     *
     * @mbggenerated
     */
    private Integer readStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbox.remove_status
     *
     * @mbggenerated
     */
    private Integer removeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbox.receipt_status
     *
     * @mbggenerated
     */
    private Integer receiptStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbox.inbox_eid
     *
     * @mbggenerated
     */
    private String inboxEid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbox.outbox_eid
     *
     * @mbggenerated
     */
    private String outboxEid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbox.draft_status
     *
     * @mbggenerated
     */
    private Integer draftStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbox.inbox_name
     *
     * @mbggenerated
     */
    private String inboxName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbox.outbox_name
     *
     * @mbggenerated
     */
    private String outboxName;
    
    private List<String> abox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inbox
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbox.inbox_id
     *
     * @return the value of inbox.inbox_id
     *
     * @mbggenerated
     */
    
    
    public Integer getInboxId() {
        return inboxId;
    }

    public List<String> getAbox() {
		return abox;
	}

	public void setAbox(List<String> abox) {
		this.abox = abox;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbox.inbox_id
     *
     * @param inboxId the value for inbox.inbox_id
     *
     * @mbggenerated
     */
    public void setInboxId(Integer inboxId) {
        this.inboxId = inboxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbox.content
     *
     * @return the value of inbox.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbox.content
     *
     * @param content the value for inbox.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbox.topic
     *
     * @return the value of inbox.topic
     *
     * @mbggenerated
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbox.topic
     *
     * @param topic the value for inbox.topic
     *
     * @mbggenerated
     */
    public void setTopic(String topic) {
        this.topic = topic == null ? null : topic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbox.createTime
     *
     * @return the value of inbox.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbox.createTime
     *
     * @param createtime the value for inbox.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbox.read_status
     *
     * @return the value of inbox.read_status
     *
     * @mbggenerated
     */
    public Integer getReadStatus() {
        return readStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbox.read_status
     *
     * @param readStatus the value for inbox.read_status
     *
     * @mbggenerated
     */
    public void setReadStatus(Integer readStatus) {
        this.readStatus = readStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbox.remove_status
     *
     * @return the value of inbox.remove_status
     *
     * @mbggenerated
     */
    public Integer getRemoveStatus() {
        return removeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbox.remove_status
     *
     * @param removeStatus the value for inbox.remove_status
     *
     * @mbggenerated
     */
    public void setRemoveStatus(Integer removeStatus) {
        this.removeStatus = removeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbox.receipt_status
     *
     * @return the value of inbox.receipt_status
     *
     * @mbggenerated
     */
    public Integer getReceiptStatus() {
        return receiptStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbox.receipt_status
     *
     * @param receiptStatus the value for inbox.receipt_status
     *
     * @mbggenerated
     */
    public void setReceiptStatus(Integer receiptStatus) {
        this.receiptStatus = receiptStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbox.inbox_eid
     *
     * @return the value of inbox.inbox_eid
     *
     * @mbggenerated
     */
    public String getInboxEid() {
        return inboxEid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbox.inbox_eid
     *
     * @param inboxEid the value for inbox.inbox_eid
     *
     * @mbggenerated
     */
    public void setInboxEid(String inboxEid) {
        this.inboxEid = inboxEid == null ? null : inboxEid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbox.outbox_eid
     *
     * @return the value of inbox.outbox_eid
     *
     * @mbggenerated
     */
    public String getOutboxEid() {
        return outboxEid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbox.outbox_eid
     *
     * @param outboxEid the value for inbox.outbox_eid
     *
     * @mbggenerated
     */
    public void setOutboxEid(String outboxEid) {
        this.outboxEid = outboxEid == null ? null : outboxEid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbox.draft_status
     *
     * @return the value of inbox.draft_status
     *
     * @mbggenerated
     */
    public Integer getDraftStatus() {
        return draftStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbox.draft_status
     *
     * @param draftStatus the value for inbox.draft_status
     *
     * @mbggenerated
     */
    public void setDraftStatus(Integer draftStatus) {
        this.draftStatus = draftStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbox.inbox_name
     *
     * @return the value of inbox.inbox_name
     *
     * @mbggenerated
     */
    public String getInboxName() {
        return inboxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbox.inbox_name
     *
     * @param inboxName the value for inbox.inbox_name
     *
     * @mbggenerated
     */
    public void setInboxName(String inboxName) {
        this.inboxName = inboxName == null ? null : inboxName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbox.outbox_name
     *
     * @return the value of inbox.outbox_name
     *
     * @mbggenerated
     */
    public String getOutboxName() {
        return outboxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbox.outbox_name
     *
     * @param outboxName the value for inbox.outbox_name
     *
     * @mbggenerated
     */
    public void setOutboxName(String outboxName) {
        this.outboxName = outboxName == null ? null : outboxName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Inbox other = (Inbox) that;
        return (this.getInboxId() == null ? other.getInboxId() == null : this.getInboxId().equals(other.getInboxId()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getTopic() == null ? other.getTopic() == null : this.getTopic().equals(other.getTopic()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getReadStatus() == null ? other.getReadStatus() == null : this.getReadStatus().equals(other.getReadStatus()))
            && (this.getRemoveStatus() == null ? other.getRemoveStatus() == null : this.getRemoveStatus().equals(other.getRemoveStatus()))
            && (this.getReceiptStatus() == null ? other.getReceiptStatus() == null : this.getReceiptStatus().equals(other.getReceiptStatus()))
            && (this.getInboxEid() == null ? other.getInboxEid() == null : this.getInboxEid().equals(other.getInboxEid()))
            && (this.getOutboxEid() == null ? other.getOutboxEid() == null : this.getOutboxEid().equals(other.getOutboxEid()))
            && (this.getDraftStatus() == null ? other.getDraftStatus() == null : this.getDraftStatus().equals(other.getDraftStatus()))
            && (this.getInboxName() == null ? other.getInboxName() == null : this.getInboxName().equals(other.getInboxName()))
            && (this.getOutboxName() == null ? other.getOutboxName() == null : this.getOutboxName().equals(other.getOutboxName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getInboxId() == null) ? 0 : getInboxId().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getTopic() == null) ? 0 : getTopic().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getReadStatus() == null) ? 0 : getReadStatus().hashCode());
        result = prime * result + ((getRemoveStatus() == null) ? 0 : getRemoveStatus().hashCode());
        result = prime * result + ((getReceiptStatus() == null) ? 0 : getReceiptStatus().hashCode());
        result = prime * result + ((getInboxEid() == null) ? 0 : getInboxEid().hashCode());
        result = prime * result + ((getOutboxEid() == null) ? 0 : getOutboxEid().hashCode());
        result = prime * result + ((getDraftStatus() == null) ? 0 : getDraftStatus().hashCode());
        result = prime * result + ((getInboxName() == null) ? 0 : getInboxName().hashCode());
        result = prime * result + ((getOutboxName() == null) ? 0 : getOutboxName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", inboxId=").append(inboxId);
        sb.append(", content=").append(content);
        sb.append(", topic=").append(topic);
        sb.append(", createtime=").append(createtime);
        sb.append(", readStatus=").append(readStatus);
        sb.append(", removeStatus=").append(removeStatus);
        sb.append(", receiptStatus=").append(receiptStatus);
        sb.append(", inboxEid=").append(inboxEid);
        sb.append(", outboxEid=").append(outboxEid);
        sb.append(", draftStatus=").append(draftStatus);
        sb.append(", inboxName=").append(inboxName);
        sb.append(", outboxName=").append(outboxName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}